### ISSUE TITLE
CY62256NLL-enrollment-microSD.fzz wiring diagram is incorrect

### ISSUE THREAD

**Issue by myndcryme** [asajim/strong-software-based-Physical-Unclonable-Function#3]
DI and DO lines (breakout board) are incorrectly routed as shown in CY62256NLL-enrollment-microSD.fzz and associated png's.  Swap DI/DO lines to fix:

- route DI (yellow) to D51
- route DO (orange) to D50

**Comment by synctext** [comment]
Thnx! Nice to see somebody diving into the real details of our PUF work. Note that this project has been on hold for a while. No new student yet to work on this.

**Comment by arefin97** [comment]
@semihost Would you please help me in Architectural design(Circuit design)?  You can mark the elements on provided images and leave some lines regarding those or by any other means.

**Comment by myndcryme** [comment]
@arefin97 - I'm happy to help, but you need to be a bit more specific.  Also, I'll warn you that it has been more than a year since I worked on this so I may be a bit rusty, but I did have it working.  At least I still have my arduino still wired up sitting next to my desk :)

**Comment by myndcryme** [comment]
I guess you probably want something like this:
![CY62256NLL-enrollment-microSD-fix_bb](https://user-images.githubusercontent.com/51213021/94972107-25ddd080-04ce-11eb-86ae-092822070887.png)

Let me know if it answers your question.

**Comment by arefin97** [comment]
@semihost Yeah, I was searching for something like this. Thanks a lot. Though I searched for raspberry Pi but for Arduino will also work fine for me.

**Comment by arefin97** [comment]
@semihost When I tried to run and upload slave_cy62256nll, It worked fine. But when I tried to run getStableBits.py in master testing folder, It showed me - "Error connecting to Arduino". I checked and this not matter or wirinig. Can you please help me in this case or provide me the codes which worked fine for you?(You can reply to me via email(provided in my profile), If want).

**Comment by myndcryme** [comment]
Make sure your device path is correct within MainEnrollment.py (line 122).  Using Debian as the host, the device doesn't show as '/dev/cu.usbmodem1411' as the original author hardcoded.  ~~IIRC on linux I think it shows as '/dev/ttyUSBx' (where x is 0, 1, etc.)~~ - you need to figure out which connected usb device is your arduino and put that inside the single quotes.  Navigate to /dev and after you plug in your Arduino you should see a new device show up.  Also, I had to change some String types to char array in .../slave-cy62256nll/src/main.cpp to get it to build without errors, but maybe that is just a problem with my build environment.  I can give specifics later when I can access the computer with the code.

**Comment by myndcryme** [comment]
I checked and my arduino shows up as /dev/ttyACM* - sorry for the confusion.

**Comment by arefin97** [comment]
@semihost Thanks for your reply. I got it and It also worked fine for me. But in  master-Enrollment folder when I ran MainEnrollment.py, by thread1 it runs enrollmentTools class and calls run() method which then calls serialPUF.check_if_it_is_working(). And in this method It checked similarity of bits it wrote and again read those. But here it showed a great desimilarity(count_wrong value is very high) and results in error. Which can be the reason here?

**Comment by jafeelv** [comment]
Is there any equivalent diagram with 23LC1024 ?

**Comment by myndcryme** [comment]
There are basic diagrams shown for early testing, but 23LC1024 proved to not be "stable" enough, which is why CY62256 was chosen.  I recall somewhere around 10% of 23LC1024 tested by the project creator were "bad" because they didn't have enough stable bits and not usable.  Years ago I did some of my own testing using various 23LC variants (indudstrial, automotive grade chips, even some 512Kbit chips) in search of higher stability and never had much success if any.  I gave up and just used CY62256.

**Comment by jafeelv** [comment]
@myndcryme  Since CY62256 is not available, I've to test with 71256SA20TPG or LY62256PL-55LLI . So, will there be any difference in the connections (comparing with CY62256) ?

**Comment by myndcryme** [comment]
You will have to carefully compare the datasheets for all differences, but I took a quick look and the pin config is different for both chips you mentioned so at minimum you will have change the wiring.  I think something like CY62256NLL-70ZC might serve as a better replacement for the obsolete PDIP chip - same specs (voltage, write cycle time, pin config, etc.) but in a TSOP package.  Just reflow it onto a PDIP adapter board.  Probably should open a new issue pertaining to SRAM availability and finding a readily available substitute to discuss this further.

**Comment by myndcryme** [comment]
Ugh... I just realized that CY62256NLL-70ZC (TSOP) is a different pin config also.

CY62256NLL-70SNCT is available (SOIC) and a pin config match for the old PDIP but obviously will need an adapter.

**Comment by jafeelv** [comment]
@myndcryme thank you for your response.. I already bought 71256SA20TPG or LY62256PL-55LLI. But, when trying to run GetStableBits.py, it generated a txt file with the below content

" 0, 8836, "

(what should be the content of the txt file if the code and SRAM is running properly?)
terminal output screenshot is attached 
![image](https://user-images.githubusercontent.com/63637416/224103904-2e753a78-115f-4acd-9af6-efe90fda3104.png)

**Comment by myndcryme** [comment]
When everything is working properly GetStableBits.py will generate a much longer list of stable bits and you will also see more output in the terminal that what you show.  I'll try to post some screenshots over the next couple of days of a properly working cy62256nll with example output for reference.

**Comment by jafeelv** [comment]
@myndcryme Thank you :)

**Comment by jafeelv** [comment]
@myndcryme do you have any idea why the goal is set as 2331 in the code GetStableBits.py ?

**Comment by myndcryme** [comment]
Sorry this took so long.  Your results should look more like what I attached.  Also, note that I modified some of the python scripts (including GetStableBits.py) when testing multiple sram's so my terminal output is a bit more verbose than default.  I'm going to close this issue because we are way off topic now so open a new issue if you need.

![getstablebits](https://user-images.githubusercontent.com/51213021/225424642-b49b0aec-7e91-4479-9677-1b22e2273e1f.png)

[strongbits-cy62256nll.txt](https://github.com/Tribler/software-based-PUF/files/10983978/strongbits-cy62256nll.txt)

**Comment by jafeelv** [comment]
@myndcryme If you could share your version of python codes, It would be helpful.
Thanks
